/* MCP tool schemas of the native server (native/mcp-server.cpp), so the Node
 * server presents the same contract to clients. Generated by
 * scripts/sync-tool-schemas.mjs; do not edit by hand. */

export const TOOL_SCHEMAS = [
  {
    "name": "open_preview",
    "description": "Render a visual preview of a 1C managed form (Form.xml, Form.form), spreadsheet template (Template.xml, .mxlx), data composition schema (СКД, Template.xml with a DataCompositionSchema root) or MXL file. Use it whenever the user wants to show a 1C form visually or see how a form or template looks (\"покажи форму\", \"открой форму\", \"как выглядит макет\"); do not show XML source and do not launch 1C:Enterprise or the configurator. A descriptor Forms/Name.xml resolves to Forms/Name/Ext/Form.xml. audience is required: \"user\" when the user asked to show or open it (a window on their screen); \"agent\" when only you need it, e.g. to check your own edit (a hidden browser the user never sees; your capture_preview images do not reach the user either). Each file gets its own preview_id and URL; earlier previews stay open and reopening a file reuses its preview. base_path or base_revision shows changes instead of the plain preview.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Form.xml, Form.form, a Forms/Name.xml descriptor, Template.xml (spreadsheet template or data composition schema), .mxlx or .mxl; absolute or workspace-relative."
        },
        "audience": {
          "type": "string",
          "enum": [
            "user",
            "agent"
          ],
          "description": "user: the user asked to see it, a window opens on their screen. agent: your own inspection, rendered hidden."
        },
        "interface_mode": {
          "type": "string",
          "enum": [
            "Auto",
            "Taxi",
            "Version85"
          ],
          "description": "Managed forms: Auto (default) infers the interface from the form; Taxi forces the legacy interface, Version85 the clean 8.5 one."
        },
        "base_path": {
          "type": "string",
          "description": "Earlier version of the same form, Template.xml or data composition schema (e.g. a copy from git or another configuration). The preview then shows what changed from base_path to path: changed properties, moved, added and removed items, cells and areas, side by side where possible."
        },
        "base_revision": {
          "type": "string",
          "description": "Compare with the same file in git instead of base_path: HEAD, HEAD~1, a branch, tag or commit, or index for the staged version. Needs a git working tree and git.exe on PATH."
        }
      },
      "required": [
        "path",
        "audience"
      ]
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "requestedPath": {
          "type": "string"
        },
        "resolvedPath": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "previewId": {
          "type": "string"
        },
        "audience": {
          "type": "string",
          "enum": [
            "user",
            "agent"
          ]
        },
        "previewUrl": {
          "type": "string"
        },
        "presentation": {
          "type": "string",
          "enum": [
            "hidden",
            "window",
            "editor",
            "client",
            "unavailable"
          ]
        },
        "kind": {
          "type": "string",
          "enum": [
            "managed-form",
            "spreadsheet-template",
            "dcs",
            "mxl",
            "xml"
          ]
        },
        "size": {
          "type": "integer"
        },
        "encoding": {
          "type": "string"
        }
      },
      "required": [
        "requestedPath",
        "resolvedPath",
        "previewUrl",
        "kind",
        "size",
        "encoding"
      ]
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "preview",
    "description": "Act on an open 1C preview; open it with open_preview first. preview_id picks the preview, the last used one by default. Operations:\ninspect — page and element ids, captions, visibility, nesting, tabs and scroll areas (narrow with query, visible_only); run it first to learn ids.\nswitch_tab — activate page_id (pages_id for a nested page set).\nselect — reveal the pages holding element_id, highlight it and scroll it into view.\nscroll — move target by delta_x/delta_y or to x/y, in pixels; element_id picks the table or spreadsheet field.\nreload — re-read the file after it changed, keeping the view.\nannotations — the user's open annotations on this preview; include_resolved adds the resolved ones.\nresolve_annotation — after handling annotation_id, mark it resolved with a short resolution; the user accepts or reopens it. Never delete the user's annotations.\nadd_annotation — pin an annotation for the user on element_id (a spreadsheet cell rNcM, to_element_id for a range) with text, to point something out; element_name labels it in the list.\nremove_annotation — delete annotation_id, only one you added.\nurl — URL of this preview and of every open one.\nclose — close preview_id, or every preview when omitted; source files are not touched.\nAnnotations (\"аннотации\", \"пометки\" in a form or template) always mean these operations: they live in the preview, not in Form.xml or Template.xml, so never add cell notes or comments to the file for them. To add some for the user: open_preview with audience=\"user\", inspect for ids (cells are rNcM), then add_annotation.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "operation": {
          "type": "string",
          "enum": [
            "inspect",
            "switch_tab",
            "select",
            "scroll",
            "reload",
            "annotations",
            "resolve_annotation",
            "add_annotation",
            "remove_annotation",
            "url",
            "close"
          ]
        },
        "preview_id": {
          "type": "string",
          "description": "Preview to act on, from open_preview; the last used preview by default."
        },
        "query": {
          "type": "string",
          "description": "inspect: narrow the listing to matching names and captions."
        },
        "visible_only": {
          "type": "boolean",
          "description": "inspect: skip hidden elements."
        },
        "page_id": {
          "type": "string",
          "description": "switch_tab: the page to activate."
        },
        "pages_id": {
          "type": "string",
          "description": "switch_tab: the nested page set that owns page_id."
        },
        "element_id": {
          "type": "string",
          "description": "select: the element to highlight; scroll: the table or spreadsheet field to move."
        },
        "target": {
          "type": "string",
          "enum": [
            "document",
            "active-page",
            "table",
            "spreadsheet"
          ],
          "description": "scroll: what to move."
        },
        "delta_x": {
          "type": "number"
        },
        "delta_y": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "include_resolved": {
          "type": "boolean",
          "description": "annotations: also list the resolved ones."
        },
        "annotation_id": {
          "type": "string",
          "description": "resolve_annotation, remove_annotation: the id from operation=annotations."
        },
        "text": {
          "type": "string",
          "description": "add_annotation: the note for the user."
        },
        "to_element_id": {
          "type": "string",
          "description": "add_annotation: last cell of a spreadsheet range, rNcM."
        },
        "element_name": {
          "type": "string",
          "description": "add_annotation: how the list names the element; cells are named R1C1 by default."
        },
        "resolution": {
          "type": "string",
          "description": "resolve_annotation: what you changed, shown to the user next to the note."
        }
      },
      "required": [
        "operation"
      ]
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "capture_preview",
    "description": "Take a PNG of an open 1C preview after navigating with preview (switch_tab, select, scroll). The image comes back to you only; to show the user, open the preview with audience=\"user\".",
    "inputSchema": {
      "type": "object",
      "properties": {
        "preview_id": {
          "type": "string",
          "description": "Preview to act on, from open_preview; the last used preview by default."
        },
        "scope": {
          "type": "string",
          "description": "viewport (default), document — the whole page, or element — element_id only.",
          "enum": [
            "viewport",
            "document",
            "element"
          ]
        },
        "element_id": {
          "type": "string",
          "description": "scope=element: an element id from preview operation=inspect."
        }
      }
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "convert_xlsx_to_template",
    "description": "Convert an Excel print form layout (.xlsx) into a 1C spreadsheet template Ext/Template.xml and open its preview. Keeps text, fonts, colors, fills, borders, alignment, sizes, merges and headers/footers; Excel defined names become named areas, a cell of exactly [Name] becomes a parameter, text containing [Name] a template. The result lists areas, parameters and what was not converted; check it with capture_preview and list_markup, then refine areas and parameters with edit_template.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "xlsx_path": {
          "type": "string",
          "description": "Path to the .xlsx workbook."
        },
        "output_path": {
          "type": "string",
          "description": "Path of the Template.xml to write, for example Templates/ПФ_MXL_Акт/Ext/Template.xml."
        },
        "sheet": {
          "type": "string",
          "description": "Sheet name; the first visible sheet by default."
        },
        "overwrite": {
          "type": "boolean",
          "description": "Replace an existing output file. Default false."
        }
      },
      "required": [
        "xlsx_path",
        "output_path"
      ]
    },
    "annotations": {
      "readOnlyHint": false,
      "destructiveHint": false
    }
  },
  {
    "name": "list_markup",
    "description": "List the markup of a 1C spreadsheet template (Template.xml): named areas with their rows/columns, parameter and template cells, all 1-based as the preview shows them.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to Template.xml."
        }
      },
      "required": [
        "path"
      ]
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "validate_template",
    "description": "Check a 1C spreadsheet template (Template.xml) for broken structure: dangling format, font or line references, cells and merges outside the grid or column set, malformed or duplicate named areas, parameter cells without names. Run it after a series of edits.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to Template.xml."
        }
      },
      "required": [
        "path"
      ]
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "edit_template",
    "description": "Edit a 1C spreadsheet template (Template.xml) in place: path, operation and that operation's arguments. Rows and columns are 1-based as in the preview. An open preview of the file refreshes; check it with capture_preview and run validate_template after a series of edits. Operations:\nset_area — name and begin_row/end_row and/or begin_column/end_column (rows only → Rows area, columns only → Columns, both → Rectangle); remove=true deletes the area.\nset_parameter — row, column and one of name, template or text; detail alone or with them.\nset_format — row, column (to_row/to_column for a range) and any of font, alignments, text_placement, indent, colors, borders, format, protection; null resets a property.\ninsert_rows, delete_rows, insert_columns, delete_columns — at, count, columns_id; merges, areas and drawings move with the grid.\nmerge_cells — row, column, rows, columns; unmerge=true splits.\nset_size — column (+to_column) with width, or row (+to_row) with height.\nset_print_settings — orientation, scale, fit_to_page, paper, copies, black_and_white, first_page_number, margins, header_size, footer_size, print_area.\nset_header_footer — kind, left/center/right texts, font; remove=true deletes it.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to Template.xml."
        },
        "operation": {
          "type": "string",
          "enum": [
            "set_area",
            "set_parameter",
            "set_format",
            "insert_rows",
            "delete_rows",
            "insert_columns",
            "delete_columns",
            "merge_cells",
            "set_size",
            "set_print_settings",
            "set_header_footer"
          ]
        },
        "name": {
          "type": "string",
          "description": "set_area: area name; set_parameter: parameter name. A 1C identifier."
        },
        "begin_row": {
          "type": "integer",
          "minimum": 1
        },
        "end_row": {
          "type": "integer",
          "minimum": 1
        },
        "begin_column": {
          "type": "integer",
          "minimum": 1
        },
        "end_column": {
          "type": "integer",
          "minimum": 1
        },
        "remove": {
          "type": "boolean",
          "description": "set_area: remove the named area; set_header_footer: remove the header or footer."
        },
        "row": {
          "type": "integer",
          "description": "The cell row (set_parameter, set_format, merge_cells) or the first row to size (set_size).",
          "minimum": 1
        },
        "column": {
          "type": "integer",
          "description": "The cell column (set_parameter, set_format, merge_cells) or the first column to size (set_size).",
          "minimum": 1
        },
        "template": {
          "type": "string",
          "description": "Text with [Name] parameters, for example «Счёт № [Номер] от [Дата]»."
        },
        "text": {
          "type": "string",
          "description": "Plain text for the cell."
        },
        "detail": {
          "type": "string",
          "description": "Drill-down parameter name; empty string removes it."
        },
        "to_row": {
          "type": "integer",
          "description": "set_format, set_size: last row of the range.",
          "minimum": 1
        },
        "to_column": {
          "type": "integer",
          "description": "set_format, set_size: last column of the range.",
          "minimum": 1
        },
        "font": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "face": {
                  "type": "string"
                },
                "size": {
                  "type": "number"
                },
                "bold": {
                  "type": "boolean"
                },
                "italic": {
                  "type": "boolean"
                },
                "underline": {
                  "type": "boolean"
                },
                "strikeout": {
                  "type": "boolean"
                }
              }
            },
            {
              "type": "null"
            }
          ],
          "description": "set_format, set_header_footer: font changes; null (set_format) returns to the inherited font."
        },
        "horizontal_alignment": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "Left",
                "Center",
                "Right",
                "Justify",
                "Auto"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "vertical_alignment": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "Top",
                "Center",
                "Bottom"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "text_placement": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "Auto",
                "Wrap",
                "Cut",
                "Block"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "indent": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "type": "null"
            }
          ]
        },
        "text_color": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "#RRGGBB or style:/web:/win:Name."
        },
        "back_color": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "As text_color."
        },
        "border_color": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "As text_color."
        },
        "border": {
          "description": "Line: a style name (None, Solid, Dotted, Dashed, DashDotted, DashDottedDotted, ThinDashed, LargeDashed, ThickDashed, Double) or { style, width }.",
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "object",
              "properties": {
                "style": {
                  "type": "string"
                },
                "width": {
                  "type": "integer",
                  "minimum": 1
                }
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "left_border": {
          "description": "As border, for one side."
        },
        "top_border": {
          "description": "As border, for one side."
        },
        "right_border": {
          "description": "As border, for one side."
        },
        "bottom_border": {
          "description": "As border, for one side."
        },
        "format": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "1C format string, e.g. ЧДЦ=2 or ДФ=dd.MM.yyyy."
        },
        "protection": {
          "type": "boolean",
          "description": "set_format: protect the cell from editing."
        },
        "at": {
          "type": "integer",
          "minimum": 1,
          "description": "Insert before this row/column, or delete starting from it."
        },
        "count": {
          "type": "integer",
          "minimum": 1,
          "description": "Rows or columns to insert or delete; 1 by default."
        },
        "columns_id": {
          "type": "string",
          "description": "Column set id for column edits; the default set when omitted."
        },
        "rows": {
          "type": "integer",
          "description": "merge_cells: height of the merged block in rows.",
          "minimum": 1
        },
        "columns": {
          "type": "integer",
          "description": "merge_cells: width of the merged block in columns.",
          "minimum": 1
        },
        "unmerge": {
          "type": "boolean",
          "description": "merge_cells: split the merge starting at row, column."
        },
        "width": {
          "type": "number",
          "description": "set_size: column width in template units.",
          "minimum": 0
        },
        "height": {
          "type": "number",
          "description": "set_size: row height in points; 0 = automatic.",
          "minimum": 0
        },
        "orientation": {
          "type": "string",
          "enum": [
            "Portrait",
            "Landscape"
          ]
        },
        "scale": {
          "type": "integer",
          "description": "set_print_settings: percent.",
          "minimum": 10,
          "maximum": 400
        },
        "fit_to_page": {
          "type": "boolean"
        },
        "paper": {
          "type": "integer",
          "description": "set_print_settings: paper size code as in Windows/Excel, 9 = A4.",
          "minimum": 0
        },
        "copies": {
          "type": "integer",
          "minimum": 0
        },
        "black_and_white": {
          "type": "boolean"
        },
        "first_page_number": {
          "type": "integer",
          "minimum": 0
        },
        "top_margin": {
          "type": "number",
          "description": "set_print_settings: mm, like the other margins and header_size/footer_size.",
          "minimum": 0
        },
        "left_margin": {
          "type": "number",
          "minimum": 0
        },
        "bottom_margin": {
          "type": "number",
          "minimum": 0
        },
        "right_margin": {
          "type": "number",
          "minimum": 0
        },
        "header_size": {
          "type": "number",
          "minimum": 0
        },
        "footer_size": {
          "type": "number",
          "minimum": 0
        },
        "print_area": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "begin_row": {
                  "type": "integer",
                  "minimum": 1
                },
                "end_row": {
                  "type": "integer",
                  "minimum": 1
                },
                "begin_column": {
                  "type": "integer",
                  "minimum": 1
                },
                "end_column": {
                  "type": "integer",
                  "minimum": 1
                }
              }
            },
            {
              "type": "null"
            }
          ],
          "description": "set_print_settings: the printed range; null clears it."
        },
        "kind": {
          "type": "string",
          "description": "set_header_footer: which one to change.",
          "enum": [
            "header",
            "footer"
          ]
        },
        "left": {
          "type": "string",
          "description": "set_header_footer: text; fields [&НомерСтраницы], [&СтраницВсего], [&Дата], [&Время]."
        },
        "center": {
          "type": "string"
        },
        "right": {
          "type": "string"
        }
      },
      "required": [
        "path",
        "operation"
      ]
    },
    "annotations": {
      "readOnlyHint": false,
      "destructiveHint": true
    }
  },
  {
    "name": "list_form_elements",
    "description": "List the items of a 1C managed form (Ext/Form.xml or its Forms/Name.xml descriptor) as a tree: name, kind (InputField, UsualGroup, Page, Table, Button…), parent and data path. edit_form addresses items by these names.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to Ext/Form.xml or the Forms/Name.xml descriptor."
        }
      },
      "required": [
        "path"
      ]
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "validate_form",
    "description": "Check a 1C managed form (Ext/Form.xml) for broken structure: duplicate ids, missing companion nodes (ContextMenu, ExtendedTooltip…), data paths without a form attribute, buttons without a command, events without a handler, main attribute count, format version. Run it after a series of edits.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to Ext/Form.xml or the Forms/Name.xml descriptor."
        }
      },
      "required": [
        "path"
      ]
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "edit_form",
    "description": "Edit a 1C managed form (Ext/Form.xml) in place: path, operation and that operation's arguments. Items are addressed by name (list_form_elements or preview operation=inspect); only the touched nodes change. An open preview of the file refreshes; check it with capture_preview and run validate_form after a series of edits. Handlers in the form module are never created or removed. Operations:\nset_properties — element (omit or Form for the form itself) and properties.\nadd_element — element (the new name), kind, into and/or after/before, optional properties; companion nodes and ids are generated.\nmove_element — element, into and/or after/before.\nremove_element — element with its companions and nested items.\nset_attribute — name, type, optional columns, title, main, saved_data, fill_check; remove=true deletes it.\nset_command — name, action, title, tooltip, shortcut, representation, modifies_saved_data, current_row_use; remove=true deletes it.\nRemoving something still referenced (by standard commands, conditional appearance, a data path or a button) is refused unless force=true.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Path to Ext/Form.xml or the Forms/Name.xml descriptor."
        },
        "operation": {
          "type": "string",
          "enum": [
            "set_properties",
            "add_element",
            "move_element",
            "remove_element",
            "set_attribute",
            "set_command"
          ]
        },
        "element": {
          "type": "string",
          "description": "Item name; add_element: the new item's name; set_properties: omit or pass Form for the form itself."
        },
        "kind": {
          "type": "string",
          "enum": [
            "InputField",
            "CheckBoxField",
            "RadioButtonField",
            "LabelField",
            "LabelDecoration",
            "PictureField",
            "PictureDecoration",
            "CalendarField",
            "TextDocumentField",
            "SpreadSheetDocumentField",
            "FormattedDocumentField",
            "ChartField",
            "Table",
            "UsualGroup",
            "ColumnGroup",
            "Pages",
            "Page",
            "Button",
            "ButtonGroup",
            "Popup",
            "CommandBar"
          ],
          "description": "add_element: the kind of item to create."
        },
        "name": {
          "type": "string",
          "description": "set_attribute, set_command: the attribute or command name."
        },
        "type": {
          "type": "string",
          "description": "set_attribute: string, string(100), string(1,fixed), boolean, number(15,2), number(15,2,nonnegative), date, dateTime, time, CatalogRef.Имя, DocumentObject.Имя, EnumRef.Имя, DefinedType.Имя, ValueTable, several joined with |, or a ready cfg:/v8:/xs: name."
        },
        "title": {
          "description": "set_attribute, set_command: a string (ru) or { ru, en }; null removes it.",
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "object"
            },
            {
              "type": "null"
            }
          ]
        },
        "tooltip": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "description": "set_command: a string (ru) or { ru, en }; null removes it."
        },
        "action": {
          "type": "string",
          "description": "set_command: the handler procedure name in the form module; the procedure itself is not created."
        },
        "shortcut": {
          "type": "string",
          "description": "set_command: for example Ctrl+Enter or F5."
        },
        "representation": {
          "type": "string",
          "enum": [
            "Auto",
            "Text",
            "Picture",
            "TextPicture"
          ]
        },
        "modifies_saved_data": {
          "type": "boolean"
        },
        "current_row_use": {
          "type": "string",
          "enum": [
            "Auto",
            "Use",
            "DontUse"
          ]
        },
        "main": {
          "type": "boolean",
          "description": "set_attribute: the main attribute of the form."
        },
        "saved_data": {
          "type": "boolean"
        },
        "fill_check": {
          "type": "string",
          "enum": [
            "ShowError",
            "DontCheck"
          ]
        },
        "columns": {
          "type": "array",
          "description": "set_attribute: columns of a ValueTable or ValueTree attribute, [{ name, type, title, remove }]; ids are numbered inside the attribute.",
          "items": {
            "type": "object"
          }
        },
        "remove": {
          "type": "boolean",
          "description": "set_attribute, set_command: delete the attribute or command."
        },
        "properties": {
          "type": "object",
          "description": "set_properties, add_element: {PropertyNode: value}, the XML node names as Designer writes them (Title, ToolTip, Visible, Enabled, ReadOnly, Width, Height, AutoMaxWidth, HorizontalStretch, VerticalStretch, TitleLocation, Group, Representation, ShowTitle…); enum values are checked and null resets to the default. Multilingual text: a string (ru) or {ru, en}. Color: style:Name, web:Name, win:Name or #RRGGBB. Font: {ref: \"style:Name\"} or {face, height, bold, italic, underline, strikeout, scale}. Picture: CommonPicture.Name or StdPicture.Name. Choice lists and role tables cannot be set.",
          "additionalProperties": true
        },
        "into": {
          "type": "string",
          "description": "add_element, move_element: target container (group, page, pages, table, command bar) or Form."
        },
        "after": {
          "type": "string",
          "description": "add_element, move_element: place after this sibling."
        },
        "before": {
          "type": "string",
          "description": "add_element, move_element: place before this sibling."
        },
        "force": {
          "type": "boolean",
          "description": "remove_element, and set_attribute/set_command with remove=true: delete even while other nodes refer to it."
        }
      },
      "required": [
        "path",
        "operation"
      ]
    },
    "annotations": {
      "readOnlyHint": false,
      "destructiveHint": true
    }
  }
] as const;
